#!/bin/bash

echo "==================STARTING BUILD=================="
pushd build &> /dev/null
gcc -Wextra -g -o libtm ../src/libtm.c
popd &> /dev/null
echo "==================BUILD FINISHED=================="