#!/bin/bash

echo "==================STARTING BUILD=================="
pushd build &> /dev/null
gcc -Wextra -Wno-address-of-packed-member -Wno-used-but-never-defined -g -o libtm ../src/libtm.c
popd &> /dev/null
echo "==================BUILD FINISHED=================="
