#!/bin/bash

echo "==================STARTING BUILD=================="
pushd build &> /dev/null
gcc -Wextra -Wno-address-of-packed-member -g -o libtm ../src/libtm.c
popd &> /dev/null
echo "==================BUILD FINISHED=================="